apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      labels:
        app: dso-demo
    spec:
      containers:
      - image: ggfsh/dso-demo
        name: dso-demo
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      automountServiceAccountToken: false
      serviceAccountName: dso-demo
      volumes:
        - name: tmp
          emptyDir: {}
status: {}
